# Generated by Django 5.1 on 2025-11-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Subway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='foto_sucursal',
            field=models.ImageField(blank=True, null=True, upload_to='sucursales/fotos/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/fotos/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='Empleado', max_length=100),
        ),
    ]
