# Generated by Django 5.1 on 2025-11-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Subway', '0002_sucursal_foto_sucursal_alter_empleado_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clientes_fotos/'),
        ),
    ]
