# Generated by Django 4.2 on 2025-11-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Subway', '0004_producto_proveedor_remove_cliente_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('alimentos', 'Proveedor de Alimentos'), ('bebidas', 'Proveedor de Bebidas'), ('materiales', 'Proveedor de Materiales'), ('equipos', 'Proveedor de Equipos'), ('general', 'Proveedor General')], default='general', max_length=50),
        ),
    ]
